Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using FPTBook.DB;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

namespace FPTBook.Controllers
{
    [Authorize(Roles = "admin")]
    public class AdminController : Controller
    {
        
        private readonly ApplicationDbContext _db;
        public AdminController(ApplicationDbContext db)
        {
            this._db = db;
        }
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult ViewListAccounts()
        {
            var lstAcc = _db.Users.ToList();
            return View(lstAcc);
        }

        public IActionResult CategoryApproval()
        {
            var lstApp = _db.Category_Requests.Include(c => c.user).ToList();
            return View(lstApp);
        }

        public IActionResult ApproveRequest(int id)
        {
            var obj = _db.Category_Requests.Find(id);
            obj.status = 1;
            var cate = _db.Categories.Where(c => c.name == obj.name).FirstOrDefault();
            cate.status = 1;
            _db.Update(cate);
            _db.Update(obj);
            _db.SaveChanges();
            return RedirectToAction(nameof(CategoryApproval));
        }
        
        public IActionResult RejectRequest(int id)
        {
            var obj = _db.Category_Requests.Find(id);
            obj.status = 1;
            var cate = _db.Categories.Where(c => c.name == obj.name).FirstOrDefault();
            cate.status = 2;
            _db.Update(cate);
            _db.Update(obj);
            _db.SaveChanges();
            return RedirectToAction(nameof(CategoryApproval));
        }
    }
    
}

Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using FPTBook.DB;
using FPTBook.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

namespace FPTBook.Controllers
{
    [Authorize]
    public class CartController : Controller
    {
        private readonly ApplicationDbContext _db;

        public CartController(ApplicationDbContext db)
        {
            this._db = db;
        }

        public IActionResult Index(string id)
        {
            var lstCart = GetLstCart();
            string userId = GetUserId();
            var cart = lstCart.Where(c => c.user_id == userId).ToList();
            return View(cart);
        }

        [HttpPost]
        public async Task<IActionResult> AddToCart(Book model, int book_id)
        {
            if(model.quantity < 1)
            {
                TempData["msg"] = "The number of quantity book to add to cart is a number greater than 1!";
                return RedirectToAction("Detail", "Home");
            }
            var book = await _db.Books.Where(b => b.id == book_id).FirstOrDefaultAsync();
            string userId = GetUserId();
            var user = await _db.Users.Where(u => u.Id == userId).FirstOrDefaultAsync();
            if (book == null)
            {
                return NotFound();
            }

            var lstCart = GetLstCart();
            var cartItem = lstCart.Find(b => b.book_id == book_id && b.user_id == userId);
            if (cartItem != null)
            {
                cartItem.quantity = cartItem.quantity + model.quantity;
                _db.Update(cartItem);
                await _db.SaveChangesAsync();
            }
            else
            {
                _db.Add(new Cart()
                {
                    book_id = book_id,
                    book = book,
                    user = user,
                    user_id = userId,
                    quantity = model.quantity,
                    date = DateTime.Now
                });
                await _db.SaveChangesAsync();
            }
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> AddCart(int book_id)
        {
            var book = await _db.Books.Where(b => b.id == book_id).FirstOrDefaultAsync();
            string userId = GetUserId();
            var user = await _db.Users.Where(u => u.Id == userId).FirstOrDefaultAsync();
            if (book == null)
            {
                return NotFound();
            }

            var lstCart = GetLstCart();
            var cartItem = lstCart.Find(b => b.book_id == book_id && b.user_id == userId);
            if (cartItem != null)
            {
                cartItem.quantity++;
                _db.Update(cartItem);
                await _db.SaveChangesAsync();
            }
            else
            {
                _db.Add(new Cart()
                {
                    book_id = book_id,
                    book = book,
                    user = user,
                    user_id = userId,
                    quantity = 1,
                    date = DateTime.Now
                });
                await _db.SaveChangesAsync();
            }
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> DeleteCart(int? id)
        {
            var cartItem = await _db.Carts.FindAsync(id);
            if (cartItem != null)
            {
                _db.Carts.Remove(cartItem);
            }
            await _db.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        public IActionResult Checkout()
        {
            var lstCart = _db.Carts.Include(c => c.user).Include(c => c.book).Include(c => c.book.category).ToList();
            string userId = GetUserId();
            var cart = lstCart.Where(c => c.user_id == userId).ToList();
            if (cart.Count == 0)
            {
                return RedirectToAction(nameof(Index));
            }
            return View(cart);
        }

        public IActionResult Order(double total)
        {
            var lstCart = GetLstCart();
            string userId = GetUserId();
            var cart = lstCart.Where(c => c.user_id == userId).ToList();
            var user = _db.Users.Where(u => u.Id == userId).FirstOrDefault();
            var book = _db.Books.ToList();
            
            foreach (var item in cart)
            {
                var itemBook = book.Where(b => b.id == item.book_id).FirstOrDefault();
                var temp = itemBook.quantity;
                temp = temp - item.quantity;
                if (temp < 0)
                {
                    TempData["msg"] = "Book with name " + itemBook.name + " has not enough quantity to buy!";
                    return RedirectToAction(nameof(Checkout));
                }
            }

            _db.Add(new Order
            {
                user = user,
                user_id = userId,
                order_date = DateTime.Now,
                address = user.address,
                payment = total,
                status = 0
            });
            _db.SaveChanges();

            var order = _db.Orders.OrderByDescending(o => o.id).Where(o => o.user_id == userId).FirstOrDefault();

            foreach (var item in cart)
            {
                _db.Add(new OrderDetail
                {
                    book = item.book,
                    book_id = item.book_id,
                    order = order,
                    order_id = order.id,
                    book_quantity = item.quantity,
                    book_price = item.book.price,
                    total = item.quantity * item.book.price

                });
                var itemBook = book.Where(b => b.id == item.book_id).FirstOrDefault();
                itemBook.quantity = itemBook.quantity - item.quantity;
                if(itemBook.quantity == 0)
                {
                    itemBook.status = 0;
                }
                _db.Update(itemBook);
            }
            _db.SaveChanges();

            foreach (var item in cart)
            {
                _db.Carts.Remove(item);
            }
            _db.SaveChanges();

            return RedirectToAction("Index", "Home");
        }

        private string GetUserId()
        {
            return Convert.ToString(HttpContext.User.FindFirstValue(ClaimTypes.NameIdentifier));
        }
        private List<Cart> GetLstCart()
        {
            return _db.Carts.Include(c => c.user).Include(c => c.book).ToList();
        }
    }
}

Controllers/CustomerController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using FPTBook.DB;
using FPTBook.Models.DTO;
using FPTBook.Models;
using FPTBook.Repositories.Abstract;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using Microsoft.AspNetCore.Identity;

namespace FPTBook.Controllers
{
    [Authorize]
    public class CustomerController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<User> userManager;
        public CustomerController( ApplicationDbContext context, UserManager<User> userManager)
        {
            this._context = context;
            this.userManager = userManager;
        }
        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> Profile(string username)
        {
            if (username == null || userManager.Users == null)
            {
                return NotFound();
            }
            var result = await _context.Users.Include(u => u.orders).FirstOrDefaultAsync(u => u.UserName == username);
            if (result == null)
            {
                return NotFound();
            }
            return View(result);
        }

        public async Task<IActionResult> Update(string id)
        {
            if (id == null || userManager.Users == null)
            {
                return NotFound();
            }

            var user = await userManager.Users.FirstOrDefaultAsync(u => u.Id == id);
            if (user == null)
            {
                return NotFound();
            }
            return View(user);
        }

        [HttpPost]
        public async Task<IActionResult> Update(User model)
        {
            var user = await userManager.FindByIdAsync(model.Id);
            var userExists = await userManager.FindByNameAsync(model.UserName);
            var emailExist = await userManager.FindByEmailAsync(model.Email);
            if(userExists != null && userExists.UserName != user.UserName){
                TempData["war"] = "The username has already existed!";
                return RedirectToAction(nameof(Update));
            }

            if (emailExist != null && emailExist.Email != user.Email)
            {
                TempData["war"] = "The email has already existed!";
                return RedirectToAction(nameof(Update));
            }
            if (user == null)
            {
                return NotFound();
            }
            else
            {
                user.full_name = model.full_name;
                user.UserName = model.UserName;
                user.Email = model.Email;
                user.gender = model.gender;
                user.PhoneNumber = model.PhoneNumber;
                user.PhoneNumberConfirmed = true;
                user.address = model.address;

            }
            var result = await userManager.UpdateAsync(user);

            if (result.Succeeded)
            {
                TempData["msg"] = "Updated successfully!";
                return RedirectToAction(nameof(Update));
            }

            foreach (var error in result.Errors)
            {
                ModelState.AddModelError("", error.Description);
            }

            return View(model);
        }

        public IActionResult CancelOrder(int id)
        {
            var order = _context.Orders.Find(id);
            var orderDetail = _context.OrderDetails.Where(od => od.order_id == order.id).ToList();
            foreach (var item in orderDetail)
            {
                var itemBook = _context.Books.ToList().Where(b => b.id == item.book_id).FirstOrDefault();
                itemBook.quantity = itemBook.quantity + item.book_quantity;
                _context.Update(itemBook);
            }
            order.status = 2;
            _context.Update(order);
            _context.SaveChanges();
            return RedirectToAction("Index", "Home");
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] FPTBook</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <!-- Google Fonts -->
    <link href='http://fonts.googleapis.com/css?family=Titillium+Web:400,200,300,700,600' rel='stylesheet'
        type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Roboto+Condensed:400,700,300' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Raleway:400,100' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <link href="~/css/bootstrap.min.css" rel="stylesheet" asp-append-version="true">
    <link href="~/css/font-awesome.min.css" rel="stylesheet" asp-append-version="true">
    <link href="~/css/animate.css" rel="stylesheet" asp-append-version="true">
    <link href="~/css/main.css" rel="stylesheet" asp-append-version="true">
    <link href="~/css/responsive.css" rel="stylesheet" asp-append-version="true">

    <link rel="stylesheet" href="~/css/style.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/FPTBook.styles.css" asp-append-version="true" />
</head>

<body>
    <header>
        <div class="header_top" style="background-color:#0621f0"><!--header_top-->
            <div class="container">
                <div class="row">
                    <div class="col-sm-6">
                        <div class="contactinfo">
                            <ul class="nav nav-pills">
                                <li><a><i class="fa fa-phone"></i> +84 0999 999 999</a></li>
                                <li><a><i class="fa fa-envelope"></i> fpt@gmail.com</a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div class="social-icons pull-right">
                            <ul class="nav navbar-nav" style="flex-direction: unset">
                                <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                                <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                                <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
                                <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div><!--/header_top-->

        <div class="header-middle" style="background-color:rgb(246, 133, 3)"><!--header-middle-->
            <div class="container">
                <div>
                    <div class="col-sm-6">
                        <div class="logo pull-left">
                            <a asp-controller="Home" asp-action="Index" style="color:#000000">
                                <img src="~/img/logo.png" alt="Logo" width="80" height="80">
                            </a>
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div class="shop-menu pull-right">
                            <partial name="_LoginPartial" />
                        </div>
                    </div>
                </div>
            </div>
        </div><!--/header-middle-->
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow mb-3"
            style="background-color:rgba(4, 251, 4, 0.859)">
            <div class="container">

                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">FPTBook</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @if (User.IsInRole("admin") || User.IsInRole("storeowner"))
                        {
                            <li class="nav-item mynav_dropdown">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="">Management<i
                                        class="fa fa-caret-down"></i></a>
                                <div class="mynav_dropdown-content">
                                    @if (User.IsInRole("storeowner"))
                                    {
                                        <a asp-controller="StoreOwner" asp-action="ViewListBooks">Book</a>
                                        <a asp-controller="StoreOwner" asp-action="ViewListCategories">Category</a>
                                        <a asp-controller="StoreOwner" asp-action="ViewListOrders">Order</a>
                                        <a asp-controller="StoreOwner" asp-action="BestSellerBook">Bestseller Book</a>
                                    }

                                    @if (User.IsInRole("admin"))
                                    {
                                        <a asp-controller="Admin" asp-action="ViewListAccounts">Account</a>
                                        <a asp-controller="Admin" asp-action="CategoryApproval">Category Approval</a>
                                    }
                                </div>
                            </li>
                        }
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-route-id="@User.Identity.Name" asp-controller="Cart"
                                asp-action="Index">Cart</a>
                        </li>
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-route-username="@User.Identity.Name"
                                asp-controller="Customer" asp-action="Profile">Profile</a>
                            </li>
                        }

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Help">Help</a>
                        </li>
                    </ul>
                    <div class="navbar-nav ms-auto pull-right">
                        <form asp-controller="Home" asp-action="Index" class="d-flex w-auto" method="GET">
                            <input name="keyword" class="form-control me-2" type="search" placeholder="Search"
                                aria-label="Search" required>
                            <button class="btn btn-outline-success" type="submit">Search</button>
                        </form>
                    </div>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <div class="footer-top-area">
        <div class="zigzag-bottom"></div>
        <div class="container">
            <div class="row">
                <div class="col-md-3 col-sm-6">
                    <div class="footer-about-us">
                        <h2>FPTBook</h2>
                        <p></p>
                        <div class="footer-social">
                            <a target="_blank"><i class="fa fa-facebook"></i></a>
                            <a href="#" target="_blank"><i class="fa fa-twitter"></i></a>
                            <a href="#" target="_blank"><i class="fa fa-youtube"></i></a>
                        </div>
                    </div>
                </div>

                <div class="col-md-3 col-sm-6">
                    <div class="footer-menu">
                        <h2 class="footer-wid-title">User</h2>
                        <ul>
                            <li><a asp-route-username="@User.Identity.Name" asp-controller="Customer"
                                    asp-action="Profile">Account</a></li>
                            <li><a asp-route-username="@User.Identity.Name" asp-controller="Customer"
                                    asp-action="Profile">Record Orders</a></li>
                            <li><a asp-controller="Home" asp-action="Help">Other information</a></li>
                        </ul>
                    </div>
                </div>

                @* <div class="col-md-3 col-sm-6">
                    <div class="footer-menu">
                        <h2 class="footer-wid-title">Classify</h2>
                        <ul>
                            <li><a href="#">Keyboards</a></li>
                            <li><a href="#">Gaming Mouse</a></li>
                            <li><a href="#">Headphones</a></li>
                        </ul>
                    </div>
                </div> *@
            </div>
        </div>
    </div> <!-- End footer top area -->

    <div class="footer-bottom-area">
        <div class="container">
            <div class="row">
                <div class="col-md-8">
                    <div class="copyright">
                        <p>&copy; 2023 - FPTBook</p>
                    </div>
                </div>

                <div class="col-md-4">
                    <div class="footer-card-icon">
                        <i class="fa fa-cc-discover"></i>
                        <i class="fa fa-cc-mastercard"></i>
                        <i class="fa fa-cc-paypal"></i>
                        <i class="fa fa-cc-visa"></i>
                    </div>
                </div>
            </div>
        </div>
    </div> <!-- End footer bottom area -->


    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.min.js" asp-append-version="true"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/silde.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>