Controllers/StoreOwnerController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using FPTBook.DB;
using FPTBook.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

namespace FPTBook.Controllers
{
    [Authorize(Roles = "storeowner")]
    public class StoreOwnerController : Controller
    {
        private readonly ApplicationDbContext _db;

        public StoreOwnerController(ApplicationDbContext db)
        {
            this._db = db;
        }
        public IActionResult ViewListBooks()
        {
            var lstBook = _db.Books.Include(b => b.category).ToList();

            return View(lstBook);
        }

        [HttpGet]
        public IActionResult ViewListBooks(string keyword)
        {
            var lstBook = _db.Books.Include(b => b.category).ToList();
            if (lstBook == null)
            {
                return NotFound();
            }
            var books = from b in _db.Books select b;
            if (!String.IsNullOrEmpty(keyword))
            {
                books = books.Where(s => s.status == 1 && s.name!.Contains(keyword));
            }

            return View(books.ToList());
        }


        public IActionResult CreateBook()
        {
            var categories = _db.Categories.Where(c => c.status == 1).ToList();
            ViewData["category_id"] = new SelectList(categories, "id", "name");
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateBook(IFormFile img, Book book)
        {
            var categories = _db.Categories.Where(c => c.status == 1).ToList();
            if (ModelState.IsValid)
            {
                var filePaths = new List<string>();
                if (img.Length > 0)
                {
                    string fileType = Path.GetExtension(img.FileName).ToLower().Trim();
                    if (fileType != ".jpg" && fileType != ".png")
                    {
                        TempData["msg"] = "File Format Not Supported. Only .jpg and .png !";
                        ViewData["category_id"] = new SelectList(categories, "id", "name");
                        return View(book);
                    }

                    var filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot\\img", img.FileName);
                    book.image = img.FileName;
                    filePaths.Add(filePath);
                    using (var stream = new FileStream(filePath, FileMode.Create))
                    {
                        await img.CopyToAsync(stream);
                    }

                    _db.Add(book);
                    await _db.SaveChangesAsync();
                    return RedirectToAction(nameof(ViewListBooks));
                }

            }
            ViewData["category_id"] = new SelectList(categories, "id", "name");
            return View(book);
        }

        public IActionResult UpdateBook(int id)
        {
            var book = _db.Books.Find(id);
            var categories = _db.Categories.Where(c => c.status == 1).ToList();
            ViewData["category_id"] = new
            // SelectList(_db.Categories, "Id", "Id", book.category_id)
            SelectList(categories, "id", "name");
            return View(book);
        }

        [HttpPost]
        public async Task<IActionResult> UpdateBook(IFormFile? img, Book book)
        {
            var categories = _db.Categories.Where(c => c.status == 1).ToList();
            if (ModelState.IsValid)
            {
                var filePaths = new List<string>();
                if (img != null && img.Length > 0)
                {
                    string fileType = Path.GetExtension(img.FileName).ToLower().Trim();
                    if (fileType != ".jpg" && fileType != ".png")
                    {
                        TempData["msg"] = "File Format Not Supported. Only .jpg and .png !";
                        ViewData["category_id"] = new SelectList(categories, "id", "name");
                        return View(book);
                    }

                    var filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot\\img", img.FileName);
                    book.image = img.FileName;
                    filePaths.Add(filePath);
                    using (var stream = new FileStream(filePath, FileMode.Create))
                    {
                        await img.CopyToAsync(stream);
                    }
                    if (book.is_deleted)
                    {
                        book.status = 2;
                    }
                    TempData["msg"] = "Updated successfully!";
                    _db.Update(book);
                    await _db.SaveChangesAsync();
                    return RedirectToAction(nameof(UpdateBook));
                }

            }
            ViewData["category_id"] = new SelectList(categories, "id", "name");
            return View(book);
        }

        public IActionResult DetailBook(int id)
        {
            var book = _db.Books.Find(id);
            if (book == null)
            {
                return RedirectToAction("Index");
            }

            return View(book);
        }

        public IActionResult DeleteBook(int id)
        {
            Book book = _db.Books.Find(id);
            if (book == null)
            {
                return RedirectToAction("Index");
            }
            book.is_deleted = true;
            book.status = 2;
            _db.Update(book);
            _db.SaveChanges();
            return RedirectToAction(nameof(ViewListBooks));
        }

        public IActionResult ViewListOrders()
        {
            var lstOrder = _db.Orders.Include(o => o.user).ToList();
            if (lstOrder == null)
            {
                return NotFound();
            }
            return View(lstOrder);
        }
        public IActionResult UpdateOrder(int id)
        {
            var order = _db.Orders.Find(id);
            if (order == null)
            {
                return NotFound();
            }
            return View(order);
        }

        [HttpPost]
        public IActionResult UpdateOrder(Order model)
        {
            var order = _db.Orders.Find(model.id);
            if (model.status != order.status || model.address != order.address)
            {
                if (model.status == 1)
                {
                    order.delivery_date = DateTime.Now;
                    // var od = _db.OrderDetails.Where(od => od.order_id == order.id).ToList();
                    // foreach (var item in od)
                    // {
                    //     var book = _db.Books.Where(b => b.id == item.book_id).FirstOrDefault();
                    //     book.quantity = book.quantity - item.book_quantity;
                    //     if(book.quantity == 0)
                    //     {
                    //         book.status = 0;
                    //     }
                    //     _db.Update(book);

                    // }
                    // _db.SaveChanges();
                }

                if (model.status == 0)
                {
                    order.delivery_date = null;
                }
                order.address = model.address;
                order.status = model.status;
                _db.Update(order);
                _db.SaveChanges();
            }
            return RedirectToAction(nameof(ViewListOrders));
        }
        public IActionResult ViewOrderDetail(int id)
        {
            var lstOrderDetail = _db.OrderDetails.Include(od => od.book).Where(od => od.order_id == id).ToList();
            if (lstOrderDetail == null)
            {
                return NotFound();
            }
            return View(lstOrderDetail);
        }
        public IActionResult ViewListCategories()
        {
            var categories = _db.Categories.ToList();
            return View(categories);
        }

        public IActionResult AddCategory()
        {
            return View();
        }

        [HttpPost]
        public IActionResult AddCategory(Category category, string username)
        {
            if (ModelState.IsValid)
            {
                category.status = 0;
                _db.Add(category);


                var user = _db.Users.Where(u => u.UserName == username).FirstOrDefault();
                _db.Add(new Category_Request
                {
                    user_id = user.Id,
                    user = user,
                    name = category.name,
                    date = DateTime.Now,
                    status = 0
                });
                _db.SaveChanges();
                return RedirectToAction(nameof(ViewListCategories));
            }
            return View(category);
        }

        public IActionResult UpdateCategory(int id)
        {
            var category = _db.Categories.Find(id);
            return View(category);
        }

        [HttpPost]
        public async Task<IActionResult> UpdateCategory(Category model)
        {
            var category = _db.Categories.Find(model.id);
            if (ModelState.IsValid)
            {
                category.name = model.name;
                category.description = model.description;
                _db.Update(category);
                await _db.SaveChangesAsync();
                return RedirectToAction(nameof(ViewListCategories));
            }
            return View(category);
        }

        public IActionResult DeleteCategory(int id)
        {
            var category = _db.Categories.Find(id);
            category.status = 3;
            var books = _db.Books.Where(b => b.category_id == category.id).ToList();
            foreach (var item in books)
            {
                item.status = 2;
                _db.Update(item);

Views/StoreOwner/AddCategory.cshtml
@model FPTBook.Models.Category

@{
    ViewData["Title"] = "AddCategory";
}

<div class="container">
    <h2>Add Category</h2>
    <form asp-action="AddCategory" method="post" class="form-horizontal" role="form">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <label class="col-sm-2 control-label">Name(*): </label>
            <div class="col-sm-10">
                <input type="text" asp-for="name" class="form-control" placeholder="Name" />
                <span class="text-danger" asp-validation-for="name"></span>
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-2 control-label">Description(*): </label>
            <div class="col-sm-10">
                <input type="text" asp-for="description" class="form-control" placeholder="Description" />
                <span class="text-danger" asp-validation-for="description"></span>
            </div>
        </div>

        @* @if (TempData["msg"] != null)
        {
            <div class="form-group">
                <div class="col-sm-2"></div>
                <div class="col-sm-10">
                    <span class="text-danger">@TempData["msg"]</span>
                </div>
            </div>
        } *@
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <input type="submit" class="btn btn-primary" value="Submit" asp-route-username="@User.Identity.Name"/>
                <button class="btn btn-primary"><a style="color: white;" type="button" 
                    asp-action="ViewListCategories">Back</a>
                </button>
            </div>
        </div>
    </form>
</div>


@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Views/StoreOwner/BestSellerBook.cshtml
@model List<FPTBook.Models.Book>

@{
    ViewData["Title"] = "BestSellerBook";
}

<h1>Bestseller Book</h1>
<table class="table">
    <thead>
        <tr>
            <th>Id</th>
            <th>Name</th>
            <th>Cat_Id</th>
            <th>Price</th>
            <th>Olde Price</th>
            <th>In Stock</th>
            <th>Image</th>
            <th>Quantity Sold</th>
            <th>Status</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            string status = "";
            @if (item.status == 0)
            {
                status = "Sold Out";
            }
            else if (item.status == 1)
            {
                status = "On Sale";
            }
            else if(item.status == 2)
            {
                status = "Inactive";
            }
            int sold = 0;
            foreach (var book in item.orders_detail)
            {
                sold = sold + book.book_quantity;
            }
            <tr>
                <td>@item.id</td>
                <td>@item.name</td>
                <td>@item.category.name</td>
                <td>@item.price</td>
                <td>@item.old_price</td>
                <td>@item.quantity</td>
                <td style="width: 100px;"><img src="~/img/@item.image" alt="@item.name" style="width: auto;"></td>
                <td>@sold</td>
                <td>@status</td>
            </tr>
        }
    </tbody>
</table>

Views/StoreOwner/CreateBook.cshtml
@model FPTBook.Models.Book

@{
    ViewData["Title"] = "CreateBook";
}

<div class="container">
    <h2>Create A New Book</h2>
    <form asp-action="CreateBook" enctype="multipart/form-data" method="post" class="form-horizontal" role="form">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <label class="col-sm-2 control-label">Name(*): </label>
            <div class="col-sm-10">
                <input type="text" asp-for="name" class="form-control" placeholder="Name" />
                <span class="text-danger" asp-validation-for="name"></span>
            </div>
        </div>

        <div class="form-group">
            <label class="col-sm-2 control-label">Author(*): </label>
            <div class="col-sm-10">
                <input type="text" asp-for="author" class="form-control" placeholder="Author" />
                <span class="text-danger" asp-validation-for="author"></span>
            </div>
        </div>

        <div class="form-group">
            <label class="col-sm-2 control-label">Date Public(*): </label>
            <div class="col-sm-10">
                <input type="date" asp-for="date" class="form-control" placeholder="Date Public" />
                <span class="text-danger" asp-validation-for="date"></span>
            </div>
        </div>

        <div class="form-group">
            <label class="col-sm-2 control-label">Description(*): </label>
            <div class="col-sm-10">
                <input type="text" asp-for="description" class="form-control" placeholder="Description" />
                <span class="text-danger" asp-validation-for="description"></span>
            </div>
        </div>

        <div class="form-group">
            <label class="col-sm-2 control-label">Quantity(*): </label>
            <div class="col-sm-10">
                <input type="number" asp-for="quantity" class="form-control" placeholder="Quantity" />
                <span class="text-danger" asp-validation-for="quantity"></span>
            </div>
        </div>

        <div class="form-group">
            <label class="col-sm-2 control-label">Old Price(*): </label>
            <div class="col-sm-10">
                <input type="number" asp-for="old_price" class="form-control" placeholder="Old Price" />
                <span class="text-danger" asp-validation-for="old_price"></span>
            </div>
        </div>

        <div class="form-group">
            <label class="col-sm-2 control-label">Price(*): </label>
            <div class="col-sm-10">
                <input type="number" asp-for="price" class="form-control" placeholder="Price" />
                <span class="text-danger" asp-validation-for="price"></span>
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-2 control-label">Image(*): </label>
            <div class="col-sm-10">
                <input type="file" name="img" class="form-control" required />
                <span class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-2 control-label">Category(*): </label>
            <div class="col-sm-10">
                <select asp-for="category_id" class="form-control" asp-items="ViewBag.category_id"></select>
                <span class="text-danger" asp-validation-for="category_id"></span>
            </div>
        </div>

        <input type="hidden" asp-for="is_deleted" value="False">
        <input type="hidden" asp-for="status" value="1">

        @if (TempData["msg"] != null)
        {
            <div class="form-group">
                <div class="col-sm-2"></div>
                <div class="col-sm-10">
                    <span class="text-danger">@TempData["msg"]</span>
                </div>
            </div>
        }
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <input type="submit" class="btn btn-primary" value="Submit" />
                <button class="btn btn-primary"><a style="color: white;" type="button" 
                    asp-action="ViewListBooks">Back to List</a>
                </button>
            </div>
        </div>
    </form>
</div>


@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Views/StoreOwner/DetailBook.cshtml
@model FPTBook.Models.Book

@{
    ViewData["Title"] = "DetailBook";
}
<div class="container">
    <div class="row">
        <div class="col-sm-6">
            <h1>Detail Book</h1>
            <table class="table">
                <tbody>
                    <tr>
                        <th>Id</th>
                        <td>@Model.id</td>
                    </tr>
                    <tr>
                        <th>Name</th>
                        <td>@Model.name</td>
                    </tr>
                    <tr>
                        <th>Author</th>
                        <td>@Model.author</td>
                    </tr>
                    <tr>
                        <th>Date Public</th>
                        <td>@Model.date</td>
                    </tr>
                    <tr>
                        <th>Description</th>
                        <td>@Model.description</td>
                    </tr>
                    <tr>
                        <th>Quantity</th>
                        <td>@Model.quantity</td>
                    </tr>
                    <tr>
                        <th>Old Price</th>
                        <td>@Model.old_price</td>
                    </tr>
                    <tr>
                        <th>Price</th>
                        <td>@Model.price</td>
                    </tr>
                    <tr>
                        <th>Category</th>
                        <td>@Model.category_id</td>
                    </tr>
                    <tr>
                        <th>Is Deleted</th>
                        <td>@Model.is_deleted</td>
                    </tr>
                    <tr>
                        <th>Status</th>
                        <td>@Model.status</td>
                    </tr>

                </tbody>
            </table>
            <a class="btn btn-outline-primary" type="button" asp-controller="StoreOwner" asp-action="UpdateBook"  asp-route-id="@Model.id"
                role="button">Update</a>
            <a class="btn btn-outline-info" role="button" asp-controller="StoreOwner"
                asp-action="ViewListBooks">Back</a>
        </div>
        <div class="col-sm-6">
            <img src="~/img/@Model.image" alt="@Model.name" style="width: 400px;">
        </div>
    </div>
</div>/

Views/StoreOwner/UpdateBook.cshtml
@model FPTBook.Models.Book

@{
    ViewData["Title"] = "UpdateBook";
}

<div class="container">
    <h2>Update Book</h2>

    <form asp-action="UpdateBook" enctype="multipart/form-data" method="post" class="form-horizontal" role="form">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <label class="col-sm-2 control-label">Name(*): </label>
            <div class="col-sm-10">
                <input type="text" asp-for="name" class="form-control" placeholder="Name" />
                <span class="text-danger" asp-validation-for="name"></span>
            </div>
        </div>

        <div class="form-group">
            <label class="col-sm-2 control-label">Author(*): </label>
            <div class="col-sm-10">
                <input type="text" asp-for="author" class="form-control" placeholder="Author" />
                <span class="text-danger" asp-validation-for="author"></span>
            </div>
        </div>

        <div class="form-group">
            <label class="col-sm-2 control-label">Date Public(*): </label>
            <div class="col-sm-10">
                <input type="date" asp-for="date" class="form-control" placeholder="Date Public" />
                <span class="text-danger" asp-validation-for="date"></span>
            </div>
        </div>

        <div class="form-group">
            <label class="col-sm-2 control-label">Description(*): </label>
            <div class="col-sm-10">
                <input type="text" asp-for="description" class="form-control" placeholder="Description" />
                <span class="text-danger" asp-validation-for="description"></span>
            </div>
        </div>

        <div class="form-group">
            <label class="col-sm-2 control-label">Quantity(*): </label>
            <div class="col-sm-10">
                <input type="number" asp-for="quantity" class="form-control" placeholder="Quantity" />
                <span class="text-danger" asp-validation-for="quantity"></span>
            </div>
        </div>

        <div class="form-group">
            <label class="col-sm-2 control-label">Old Price(*): </label>
            <div class="col-sm-10">
                <input type="number" asp-for="old_price" class="form-control" placeholder="Old Price" />
                <span class="text-danger" asp-validation-for="old_price"></span>
            </div>
        </div>

        <div class="form-group">
            <label class="col-sm-2 control-label">Price(*): </label>
            <div class="col-sm-10">
                <input type="number" asp-for="price" class="form-control" placeholder="Price" />
                <span class="text-danger" asp-validation-for="price"></span>
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-2 control-label">Image(*): </label>
            <div class="col-sm-10">
                <input type="file" name="img" class="form-control" required />
                <span class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-2 control-label">Category(*): </label>
            <div class="col-sm-10">
                <select asp-for="category_id" class="form-control" asp-items="ViewBag.category_id"></select>
                <span class="text-danger" asp-validation-for="category_id"></span>
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-2 control-label">Is Deleted(*): </label>
            <div class="col-sm-10">
                <select asp-for="is_deleted">
                    <option value="False">Fasle</option>
                    <option value="True">True</option>
                </select>
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-2 control-label">Status(*): </label>
            <div class="col-sm-10">
                <select asp-for="status">
                    <option value="1">On sale</option>
                    <option value="0">Sold out</option>
                    <option value="2">Inactive</option>
                </select>
            </div>
        </div>

        @* <input type="hidden" asp-for="is_deleted" value="False"> *@
        @* <input type="hidden" asp-for="status" value="1"> *@



        @if (TempData["msg"] != null)
        {
            <div class="form-group">
                <div class="col-sm-2"></div>
                <div class="col-sm-10">
                    <span class="text-danger">@TempData["msg"]</span>
                </div>
            </div>
        }
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <input type="submit" class="btn btn-primary" value="Submit" />
                <button class="btn btn-primary"><a style="color: white;" type="button" asp-action="ViewListBooks">Back
                        to List</a>
                </button>
            </div>
        </div>
    </form>
</div>


@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Views/StoreOwner/UpdateCategory.cshtml
@model FPTBook.Models.Category

@{
    ViewData["Title"] = "UpdateCategory";
}

<div class="container">
    <h2>Update Category</h2>
    <form asp-action="UpdateCategory" method="post" class="form-horizontal" role="form">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <label class="col-sm-2 control-label">Name(*): </label>
            <div class="col-sm-10">
                <input type="text" asp-for="name" class="form-control" placeholder="@Model.name" />
                <span class="text-danger" asp-validation-for="name"></span>
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-2 control-label">Description(*): </label>
            <div class="col-sm-10">
                <input type="text" asp-for="description" class="form-control" placeholder="@Model.description" />
                <span class="text-danger" asp-validation-for="description"></span>
            </div>
        </div>

        @* @if (TempData["msg"] != null)
        {
            <div class="form-group">
                <div class="col-sm-2"></div>
                <div class="col-sm-10">
                    <span class="text-danger">@TempData["msg"]</span>
                </div>
            </div>
        } *@
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <input type="submit" class="btn btn-primary" value="Submit" />
                <button class="btn btn-primary"><a style="color: white;" type="button" 
                    asp-action="ViewListCategories">Back</a>
                </button>
            </div>
        </div>
    </form>
</div>

Views/StoreOwner/UpdateOrder.cshtml
@model FPTBook.Models.Order

@{
    ViewData["Title"] = "UpdateOrder";
}

<h1>Order</h1>
<form asp-action="UpdateOrder" method="post" role="form">
    <div class="form-group">
        <label class="control-label">Address</label>
        <textarea asp-for="@Model.address" cols="20" rows="5"></textarea>
    </div>
    <div class="form-group">
        <label class="control-label">Status</label>
        <select asp-for="status" class ="form-control" >
        <option value="0" selected>Packing</option>
        <option value="1" >Deliveried</option>
        </select>
    </div>
    <input type="submit" class="btn btn-primary" value="Submit" />
    <button class="btn btn-primary"><a style="color: white;" asp-action="ViewListOrders">Back to
                    List</a></button>
</form>

Views/StoreOwner/ViewListBooks.cshtml
@model List<FPTBook.Models.Book>

@{
    ViewData["Title"] = "ViewListBooks";
}
<h1>Manage Book</h1>
<p>
    <button class="btn btn-primary"><a style="color: white;" asp-action="CreateBook">Add</a></button>
</p>
<div class="navbar-nav ms-auto pull-right">
    <form asp-controller="StoreOwner" asp-action="ViewListBooks" class="d-flex w-auto" method="GET">
        <input name="keyword" class="form-control me-2" type="search" placeholder="Search" aria-label="Search" required>
        <button class="btn btn-outline-success" type="submit">Search</button>
    </form>
</div>
<table class="table">
    <thead>
        <tr>
            <th>Id</th>
            <th>Cat_Id</th>
            <th>Name</th>
            <th>Author</th>
            <th>Date</th>
            <th>Description</th>
            <th>In Stock</th>
            <th>Olde Price</th>
            <th>Price</th>
            <th>Image</th>
            <th>Deleted</th>
            <th>Status</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            string status = "";
            @if (item.status == 0)
            {
                status = "Sold Out";
            }
            else if (item.status == 1)
            {
                status = "On Sale";
            }
            else if (item.status == 2)
            {
                status = "Inactive";
            }
            <tr>
                <td>@item.id</td>
                <td>@item.category.name</td>
                <td>@item.name</td>
                <td>@item.author</td>
                <td>@item.date.ToString("dd/MM/yyyy")</td>
                <td>@item.description</td>
                <td>@item.quantity</td>
                <td>@item.old_price</td>
                <td>@item.price</td>
                <td style="width: 100px;"><img src="~/img/@item.image" alt="@item.name" style="width: auto;"></td>
                <td>@item.is_deleted</td>
                <td>@status</td>
                <td>
                    <a asp-action="UpdateBook" asp-route-id="@item.id">Update</a> |
                    <a asp-action="DetailBook" asp-route-id="@item.id">Details</a> |
                    <a asp-action="DeleteBook" asp-route-id="@item.id"
                        onclick="return confirm('Are you sure about that?')">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

Views/StoreOwner/ViewOrderDetail.cshtml
@model List<FPTBook.Models.OrderDetail>

@{
    ViewData["Title"] = "ViewOrderDetail";
}

<h1>Order Detail</h1>
<a class="btn btn-primary" type="button" asp-controller="StoreOwner" asp-action="ViewListOrders" role="button">Back to list</a>
<table class="table">
    <thead>
        <tr>
            <th>Id</th>
            <th>Order Id</th>
            <th>Book</th>
            <th>Quantity</th>
            <th>Price</th>
            <th>Total</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            double total = @item.book_quantity * @item.book.price;
            <tr>
                <td>@item.id</td>
                <td>@item.order_id</td>
                <td>@item.book.name</td>
                <td>@item.book_quantity</td>
                <td>@item.book.price</td>
                <td>$@total</td>
            </tr>
        }
    </tbody>
</table>